# Hey Emacs, this is a -*- makefile -*-
#
# Copyright (C) 2013 Gautier Hattenberger
#
# This file is part of paparazzi.
#
# paparazzi is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# paparazzi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with paparazzi; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#

# General ocaml compiling tools and pprz lib

# error if PAPARAZZI_SRC is not set and trying to compile
ifneq ($(MAKECMDGOALS),clean)
ifeq ($(PAPARAZZI_SRC),)
  $(error PAPARAZZI_SRC not set, please set it manually or invoke make from the toplevel paparazzi dir)
endif
endif

OCAML = ocaml
OCAMLC = ocamlfind ocamlc -safe-string -g -thread
OCAMLOPT = ocamlfind ocamlopt -safe-string -g -thread
OCAMLDEP = ocamlfind ocamldep
OCAMLMKLIB = ocamlmklib
OCAMLLEX=ocamllex
OCAMLYACC=ocamlyacc
OCAMLLIBDIR=$(shell $(OCAMLC) -where)
OCAML_CONFIG=$(shell $(OCAMLC) -config)
OCAML_VERSION=$(shell printf '%s\n' "$(OCAML_CONFIG)" | sed -n 's/^version: //p')
OCAML_EXEC_MAGIC=$(shell printf '%s\n' "$(OCAML_CONFIG)" | sed -n 's/^exec_magic_number: //p')
OCAML_STAMP=.ocaml-toolchain
LIBPPRZLINKDIR = $(PAPARAZZI_HOME)/var/lib/ocaml
LIBPPRZDIR = $(PAPARAZZI_SRC)/sw/lib/ocaml
LIBPPRZCMA = $(LIBPPRZDIR)/lib-pprz.cma
LIBPPRZCMXA = $(LIBPPRZCMA:.cma=.cmxa)
XLIBPPRZCMA = $(LIBPPRZDIR)/xlib-pprz.cma
XLIBPPRZCMXA = $(XLIBPPRZCMA:.cma=.cmxa)
LIBPPRZLINKCMA = $(LIBPPRZLINKDIR)/pprzlink/lib-pprzlink.cma
LIBPPRZLINKCMXA = $(LIBPPRZLINKCMA:.cma=.cmxa)
OCAMLDLL = -dllpath $(LIBPPRZDIR),$(LIBPPRZLINKDIR)
OCAMLXDLL = -dllpath $(LIBPPRZDIR),$(LIBPPRZLINKDIR)

OCAMLPATH:=$(shell echo $(LIBPPRZLINKDIR):$(LIBPPRZDIR):$(OCAMLPATH))
export OCAMLPATH

$(OCAML_STAMP): Makefile
	@printf '%s\n' 'version=$(OCAML_VERSION)' 'exec_magic=$(OCAML_EXEC_MAGIC)' > $@.tmp
	@if ! cmp -s $@.tmp $@; then mv $@.tmp $@; else rm -f $@.tmp; fi

# Test lablgtk version, use V2 if available, V3 otherwise
# disable ocaml/gtk tools if none ?
LABLGTK2_VER = $(shell ocamlfind query -p-format lablgtk2 2>/dev/null)
LABLGTK3_VER = $(shell ocamlfind query -p-format lablgtk3 2>/dev/null)
ifneq ($(LABLGTK2_VER),)
USE_LABELGTK = $(LABLGTK2_VER)
else
ifneq ($(LABLGTK3_VER),)
USE_LABELGTK = $(LABLGTK3_VER)
else
USE_LABELGTK=
endif
endif
