#include "firmwares/rotorcraft/stabilization/stabilization_andi.h"
#include<math.h>

#if ANDI_NUM_ACT != 4
#error Cyclone expects 4 actuators
#endif

#if ANDI_OUTPUTS != 4
#error The cyclone model provides 4 outputs
#endif

union CycloneCoefficients {
  struct {
    // X-axis force coefficients (f_ff_x)
    float fx_motor_squared;          // Motor thrust squared effect
    float fx_speed_forward;          // Forward speed effect

    // Y-axis force coefficients (f_ff_y) 
    float fy_speed_lateral;          // Lateral speed effect

    // Z-axis force coefficients (f_ff_z)
    float fz_motor_squared;          // Motor thrust squared effect
    float fz_speed_forward;          // Forward speed effect
    float fz_speed_vertical;         // Vertical speed effect
    float fz_elevon_speed;           // Elevon-speed coupling
    float fz_elevon_motor;           // Elevon-motor coupling

    // X-axis moment coefficients (m_ff_x)
    float mx_motor_diff;             // (motor_l^2 - motor_r^2)
    float mx_elevon_motor_diff;      // (ele_l * motor_l^2 - ele_r * motor_r^2)
    float mx_elevon_speed_diff;      // (ele_l - ele_r) * speed * v_ff(1)
    float mx_angular_coupling;       // w_ff(2) * w_ff(3)

    // Y-axis moment coefficients (m_ff_y)
    float my_speed_forward;          // speed * v_ff(1)
    float my_speed_vertical;         // speed * v_ff(3)
    float my_constant_zero;          // constant 0 term
    float my_motor_sum;              // motor_l^2 + motor_r^2
    float my_elevon_motor_sum;       // ele_l * motor_l^2 + ele_r * motor_r^2
    float my_elevon_speed_sum;       // (ele_l + ele_r) * speed * v_ff(1)
    float my_angular_sum;            // w_ff(1) + w_ff(3)

    // Z-axis moment coefficients (m_ff_z)
    float mz_speed_lateral;          // speed * v_ff(2)
    float mz_motor_diff;             // motor_l^2 - motor_r^2
    float mz_speed_roll;             // speed * w_ff(1)
    float mz_angular_coupling;       // w_ff(1) * w_ff(2)
  };
  float data[23];
}; 

// Model coefficinets
// union CycloneCoefficients obm_coefficients = {
//   .fx_motor_squared       = 0.00000735f,
//   .fx_speed_forward       = -0.03f,

//   .fy_speed_lateral       = -0.008f,

//   .fz_motor_squared       = 0.0f,
//   .fz_speed_forward       = 0.0f,
//   .fz_speed_vertical      = -0.144f,
//   .fz_elevator_speed      = 0.0f,
//   .fz_elevator_motor      = 0.0f,

//   .mx_motor_diff          = 0.0f,
//   .mx_elevator_motor_diff = 0.0000283f,
//   .mx_elevator_speed_diff = 0.344f,
//   .mx_angular_coupling    = -2.18f,

//   .my_speed_forward       = 0.0f,
//   .my_speed_vertical      = -0.0888f,
//   .my_constant_zero       = -1.032f,
//   .my_motor_sum           = 0.0f,
//   .my_elevator_motor_sum  = -0.0000424f,
//   .my_elevator_speed_sum  = -0.2525f,
//   .my_angular_sum         = 1.262f,

//   .mz_speed_lateral       = -0.00371f,
//   .mz_motor_diff          = 0.000039f,
//   .mz_speed_roll          = -0.0129f,
//   .mz_angular_coupling    = -0.4827f
// };

union CycloneCoefficients obm_coefficients = {
  .fx_motor_squared       = 0.00000735f,
  .fx_speed_forward       = -0.03f,

  .fy_speed_lateral       = -0.008f,

  .fz_motor_squared       = 0.0f,
  .fz_speed_forward       = 0.0f,
  .fz_speed_vertical      = -0.144f,
  .fz_elevon_speed        = 0.0f,
  .fz_elevon_motor        = 0.0f,

  .mx_motor_diff          = 0.0f,
  .mx_elevon_motor_diff   = 0.0000283f,
  .mx_elevon_speed_diff   = 0.344f,
  .mx_angular_coupling    = -2.18f,

  .my_speed_forward       = 0.0f,
  .my_speed_vertical      = -0.0888f,
  .my_constant_zero       = -1.032f,
  .my_motor_sum           = 0.0f,
  .my_elevon_motor_sum    = -0.0000624f, // -0.0000424f, // Increase effectiveness in an attempt to fix oscillations in the eleons in pitch
  .my_elevon_speed_sum    = -0.2525f,
  .my_angular_sum         = 1.262f,

  .mz_speed_lateral       = -0.00371f,
  .mz_motor_diff          = 0.000039f,
  .mz_speed_roll          = -0.0129f,
  .mz_angular_coupling    = -0.4827f
};

/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cyclone_f_stb_u.c
 *
 * Code generation for function 'cyclone_f_stb_u'
 *
 */

/* Function Definitions */
static void cyclone_f_stb_u(const float body_vel[3], const float u[4],
                            const float coeff[23], float F_stb_u[16])
{
  float fv[16];
  float t6;
  float t7;
  int i;
  int i1;
  int i2;
  /* CYCLONE_F_STB_U */
  /*     F_stb_u = CYCLONE_F_STB_U(IN1,IN2,IN3,IN4,IN5) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-11-04 20:55:24 */
  t6 = sqrtf((body_vel[0] * body_vel[0] + body_vel[1] * body_vel[1]) +
             body_vel[2] * body_vel[2]);
  t7 = coeff[10] * t6 * body_vel[2];
  t6 = coeff[17] * t6 * body_vel[2];
  fv[0] = 0.0F;
  fv[1] = -t6 + u[2] * coeff[16];
  fv[2] = t7 - u[2] * coeff[9];
  fv[3] = 0.0F;
  fv[4] = 0.0F;
  fv[5] = -t6 + u[3] * coeff[16];
  fv[6] = -t7 + u[3] * coeff[9];
  fv[7] = 0.0F;
  fv[8] = coeff[20];
  fv[9] = coeff[15] + u[0] * coeff[16];
  fv[10] = -coeff[8] - u[0] * coeff[9];
  fv[11] = coeff[0];
  fv[12] = -coeff[20];
  fv[13] = coeff[15] + u[1] * coeff[16];
  fv[14] = coeff[8] + u[1] * coeff[9];
  fv[15] = coeff[0];
  i = 0;
  i1 = 0;
  for (i2 = 0; i2 < 16; i2++) {
    F_stb_u[i1 + (i << 2)] = fv[i2];
    i++;
    if (i > 3) {
      i = 0;
      i1++;
    }
  }
}

/* End of code generation (cyclone_f_stb_u.c) */


/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * cyclone_f_stb_x.c
 *
 * Code generation for function 'cyclone_f_stb_x'
 *
 */

/* Function Definitions */
static void cyclone_f_stb_x(const float rates[3], const float vel_body[3],
                     const float actuator_state[4],
                     const float obm_coefficients[23], float F_stb_x[24])
{
  float fv1[24];
  float fv[2];
  float f;
  float f1;
  float mt1_tmp;
  float t10;
  float t12;
  float t15;
  float t17;
  float t17_tmp;
  float t19;
  float t8;
  int i;
  int i1;
  int i2;
  /* CYCLONE_F_STB_X */
  /*     F_stb_x = CYCLONE_F_STB_X(IN1,IN2,IN3,IN4,IN5) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-10-31 18:21:48 */
  t8 = vel_body[1] * obm_coefficients[19];
  t10 = vel_body[0] * vel_body[0];
  t12 = vel_body[2] * vel_body[2];
  t15 = actuator_state[0] - actuator_state[1];
  t17_tmp = rates[2] * obm_coefficients[21];
  t17 = t8 - t17_tmp;
  t19 = sqrtf((t10 + vel_body[1] * vel_body[1]) + t12);
  fv[0] = 1.0E-8F;
  fv[1] = t19;
  mt1_tmp = fmaxf(fv[0], fv[1]);
  fv1[0] = t17 * vel_body[0] / mt1_tmp;
  f = actuator_state[0] * obm_coefficients[17];
  f1 = actuator_state[1] * obm_coefficients[17];
  fv1[1] = -((((-obm_coefficients[13] * t10 +
                vel_body[0] * obm_coefficients[12] * vel_body[2]) -
               obm_coefficients[13] * t19 * mt1_tmp) +
              f * vel_body[0] * vel_body[2]) +
             f1 * vel_body[0] * vel_body[2]) /
           mt1_tmp;
  t10 = obm_coefficients[10] * t15;
  fv1[2] = t10 * vel_body[0] * vel_body[2] / mt1_tmp;
  fv1[3] = 0.0F;
  fv1[4] = ((t8 * vel_body[1] + -t17_tmp * vel_body[1]) +
            obm_coefficients[19] * t19 * mt1_tmp) /
           mt1_tmp;
  fv1[5] = -(vel_body[1] * (((-obm_coefficients[13] * vel_body[0] +
                              vel_body[2] * obm_coefficients[12]) +
                             f * vel_body[2]) +
                            f1 * vel_body[2])) /
           mt1_tmp;
  fv1[6] = t10 * vel_body[1] * vel_body[2] / mt1_tmp;
  fv1[7] = 0.0F;
  fv1[8] = t17 * vel_body[2] / mt1_tmp;
  fv1[9] = -((((((obm_coefficients[12] * t12 + f * t12) + f1 * t12) -
                vel_body[0] * obm_coefficients[13] * vel_body[2]) +
               obm_coefficients[12] * t19 * mt1_tmp) +
              f * t19 * mt1_tmp) +
             f1 * t19 * mt1_tmp) /
           mt1_tmp;
  fv1[10] = t10 * t19 + obm_coefficients[10] * t12 * t15 / mt1_tmp;
  fv1[11] = 0.0F;
  fv1[12] = 0.0F;
  fv1[13] = obm_coefficients[18];
  fv1[14] = -obm_coefficients[11] * rates[1];
  fv1[15] = 0.0F;
  fv1[16] = -obm_coefficients[22] * rates[2];
  fv1[17] = 0.0F;
  fv1[18] = -obm_coefficients[11] * rates[0];
  fv1[19] = 0.0F;
  fv1[20] = -obm_coefficients[21] * t19 - rates[1] * obm_coefficients[22];
  fv1[21] = -obm_coefficients[18];
  fv1[22] = 0.0F;
  fv1[23] = 0.0F;
  i = 0;
  i1 = 0;
  for (i2 = 0; i2 < 24; i2++) {
    F_stb_x[i1 + 6 * i] = fv1[i2];
    i++;
    if (i > 3) {
      i = 0;
      i1++;
    }
  }
}

/* End of code generation (cyclone_f_stb_x.c) */


void evaluate_obm_f_stb_u(float fu_mat[ANDI_NUM_ACT * ANDI_OUTPUTS], const struct FloatRates *rates, const struct FloatVect3 *vel_body, const float actuator_state[ANDI_NUM_ACT])
{
  float vel_body_array[3];
  (void)rates; 

  vel_body_array[0] = vel_body->x;
  vel_body_array[1] = vel_body->y;
  vel_body_array[2] = vel_body->z;

  cyclone_f_stb_u(vel_body_array, actuator_state, obm_coefficients.data, fu_mat);
}

// void evaluate_obm_f_stb_x(float fx_mat[ANDI_NUM_STATES * ANDI_OUTPUTS], const struct FloatRates *rates, const struct FloatVect3 *vel_body, const float actuator_state[ANDI_NUM_ACT])
// {
//   float rates_array[3];
//   float vel_body_array[3];

//   rates_array[0] = rates->p;
//   rates_array[1] = rates->q;
//   rates_array[2] = rates->r;

//   vel_body_array[0] = vel_body->x;
//   vel_body_array[1] = vel_body->y;
//   vel_body_array[2] = vel_body->z;

//   cyclone_f_stb_x(rates_array, vel_body_array, actuator_state, obm_coefficients.data, fx_mat);
// }

float evaluate_obm_thrust(const float actuator_state[ANDI_NUM_ACT])
{
  return obm_coefficients.fx_motor_squared * (actuator_state[2] + actuator_state[3]);
}