# Hey Emacs, this is a -*- makefile -*-

DESTDIR=/

ifeq ($(PAPARAZZI_HOME),)
PAPARAZZI_HOME=$(HOME)/paparazzi
endif

ifeq ($(PAPARAZZI_SRC),)
GENERATORS=$(DESTDIR)/usr/share/paparazzi/bin
else
GENERATORS=$(PAPARAZZI_SRC)/sw/tools/generators
endif

# This i9-14900HX builds fastest on its 16 P-core threads. Override either
# variable on the make command line to tune or disable this local scheduling.
J ?= 16
BUILD_CPUSET ?= 0-15

