/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: compute_lin_acc_control_rf_aero_only.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 03-May-2024 02:28:05
 */

/* Include Files */
#include "compute_lin_acc_control_rf_aero_only.h"
#include "rt_nonfinite.h"
#include <math.h>
#include <string.h>

/* Function Definitions */
/*
 * COMPUTE_LIN_ACC_CONTROL_RF_AERO_ONLY
 *     ACCELERATIONS_ARRAY =
 * COMPUTE_LIN_ACC_CONTROL_RF_AERO_ONLY(Beta,Cd_zero,Cl_alpha,K_Cd,Phi,S,Theta,V,FLIGHT_PATH_ANGLE,M,RHO)
 *
 * Arguments    : double Beta
 *                double Cd_zero
 *                double Cl_alpha
 *                double K_Cd
 *                double Phi
 *                double S
 *                double Theta
 *                double V
 *                double flight_path_angle
 *                double m
 *                double rho
 *                double accelerations_array[3]
 * Return Type  : void
 */
void c_compute_lin_acc_control_rf_ae(double Beta, double Cd_zero,
                                     double Cl_alpha, double K_Cd, double Phi,
                                     double S, double Theta, double V,
                                     double flight_path_angle, double m,
                                     double rho, double accelerations_array[3])
{
  double t11;
  double t12;
  double t13;
  double t14;
  double t17;
  double t19_tmp;
  double t21_tmp_tmp;
  double t23;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     02-May-2024 14:33:14 */
  t3 = cos(Phi);
  t4 = sin(Beta);
  t5 = cos(Theta);
  t6 = sin(Phi);
  t7 = sin(Theta);
  t9 = V * V;
  t11 = 1.0 / m;
  t12 = Theta - flight_path_angle;
  t13 = cos(t12);
  t14 = sin(t12);
  t19_tmp = Cl_alpha * S * rho * t9 * t12;
  t17 = Cd_zero + K_Cd * (Cl_alpha * Cl_alpha) * (t12 * t12);
  t21_tmp_tmp = S * rho;
  t12 = t21_tmp_tmp * cos(Beta) * t9;
  t23 = t19_tmp * t13 / 2.0 + t12 * t14 * t17 / 2.0;
  t12 = t19_tmp * t14 / 2.0 - t12 * t13 * t17 / 2.0;
  t13 = t21_tmp_tmp * t4;
  accelerations_array[0] =
      -t11 * ((-t5 * t12 + t3 * t7 * t23) + t13 * t6 * t7 * t9 * t17 / 2.0);
  accelerations_array[1] =
      t11 * (t6 * t23 - t21_tmp_tmp * t3 * t4 * t9 * t17 / 2.0);
  accelerations_array[2] =
      -t11 * ((t7 * t12 + t3 * t5 * t23) + t13 * t5 * t6 * t9 * t17 / 2.0) +
      9.81;
}

/*
 * File trailer for compute_lin_acc_control_rf_aero_only.c
 *
 * [EOF]
 */
