#ifndef MATEKF405_TE_SD_H
#define MATEKF405_TE_SD_H
#ifndef BOARD_OTG_NOVBUSSENS
#define BOARD_OTG_NOVBUSSENS 1
#endif

#define BOARD_MATEK_F405_TE_SD

#include "board.h"
#include "mcuconf_board.h"

#define AHB_CLK STM32_HCLK
#define EXT_CLK 8000000

#define _CONCAT_BOARD_PARAM(_s1, _s2) _s1 ## _s2
#define CONCAT_BOARD_PARAM(_s1, _s2) _CONCAT_BOARD_PARAM(_s1, _s2)

#ifndef USE_LED_1
#define USE_LED_1 1
#endif
#define LED_1_GPIO PAL_PORT(LINE_LED1)
#define LED_1_GPIO_PIN PAL_PAD(LINE_LED1)
#define LED_1_GPIO_ON gpio_clear
#define LED_1_GPIO_OFF gpio_set

#ifndef USE_LED_2
#define USE_LED_2 1
#endif
#define LED_2_GPIO PAL_PORT(LINE_LED2)
#define LED_2_GPIO_PIN PAL_PAD(LINE_LED2)
#define LED_2_GPIO_ON gpio_clear
#define LED_2_GPIO_OFF gpio_set

#define BOARD_LEDS_INV TRUE

#ifndef USE_ADC_1
#define USE_ADC_1 1
#endif
#if USE_ADC_1
#define AD1_1_CHANNEL 14
#define ADC_1 AD1_1
#define ADC_1_GPIO_PORT PAL_PORT(LINE_BATT_VOLTAGE_SENS)
#define ADC_1_GPIO_PIN PAL_PAD(LINE_BATT_VOLTAGE_SENS)
#endif

#ifndef USE_ADC_2
#define USE_ADC_2 1
#endif
#if USE_ADC_2
#define AD1_2_CHANNEL 15
#define ADC_2 AD1_2
#define ADC_2_GPIO_PORT PAL_PORT(LINE_BATT_CURRENT_SENS)
#define ADC_2_GPIO_PIN PAL_PAD(LINE_BATT_CURRENT_SENS)
#endif

#ifndef USE_ADC_3
#define USE_ADC_3 1
#endif
#if USE_ADC_3
#define AD1_3_CHANNEL 8
#define ADC_3 AD1_3
#define ADC_3_GPIO_PORT PAL_PORT(LINE_RSSI_ADC_PIN)
#define ADC_3_GPIO_PIN PAL_PAD(LINE_RSSI_ADC_PIN)
#endif

#ifndef USE_ADC_4
#define USE_ADC_4 1
#endif
#if USE_ADC_4
#define AD1_4_CHANNEL 10
#define ADC_4 AD1_4
#define ADC_4_GPIO_PORT PAL_PORT(LINE_PRESSURE_SENS)
#define ADC_4_GPIO_PIN PAL_PAD(LINE_PRESSURE_SENS)
#endif

#ifndef ADC_CHANNEL_VSUPPLY
#define ADC_CHANNEL_VSUPPLY ADC_1
#endif
#ifndef ADC_CHANNEL_CURRENT
#define ADC_CHANNEL_CURRENT ADC_2
#endif

#define DefaultVoltageOfAdc(adc) ((3.3f/4096.0f)*20.9318f*(adc))
#define DefaultMilliAmpereOfAdc(adc) ((3.3f/4096.0f)*(1000.0f/0.0317f)*(adc))

#ifndef USE_PWM_TIM1
#define USE_PWM_TIM1 1
#endif
#ifndef USE_PWM_TIM2
#define USE_PWM_TIM2 1
#endif
#ifndef USE_PWM_TIM3
#define USE_PWM_TIM3 1
#endif
#ifndef USE_PWM_TIM4
#define USE_PWM_TIM4 1
#endif
#ifndef USE_PWM_TIM8
#define USE_PWM_TIM8 1
#endif
#ifndef USE_PWM_TIM12
#define USE_PWM_TIM12 1
#endif

#ifndef USE_PWM1
#define USE_PWM1 1
#endif
#if USE_PWM1
#define PWM_SERVO_1 1
#define PWM_SERVO_1_GPIO PAL_PORT(LINE_SERVO1)
#define PWM_SERVO_1_PIN PAL_PAD(LINE_SERVO1)
#define PWM_SERVO_1_AF AF_SERVO1
#define PWM_SERVO_1_DRIVER PWMD8
#define PWM_SERVO_1_CHANNEL 3
#define PWM_SERVO_1_CONF pwmcfg8
#endif

#ifndef USE_PWM2
#define USE_PWM2 1
#endif
#if USE_PWM2
#define PWM_SERVO_2 2
#define PWM_SERVO_2_GPIO PAL_PORT(LINE_SERVO2)
#define PWM_SERVO_2_PIN PAL_PAD(LINE_SERVO2)
#define PWM_SERVO_2_AF AF_SERVO2
#define PWM_SERVO_2_DRIVER PWMD8
#define PWM_SERVO_2_CHANNEL 2
#define PWM_SERVO_2_CONF pwmcfg8
#endif

#ifndef USE_PWM3
#define USE_PWM3 1
#endif
#if USE_PWM3
#define PWM_SERVO_3 3
#define PWM_SERVO_3_GPIO PAL_PORT(LINE_SERVO3)
#define PWM_SERVO_3_PIN PAL_PAD(LINE_SERVO3)
#define PWM_SERVO_3_AF AF_SERVO3
#define PWM_SERVO_3_DRIVER PWMD1
#define PWM_SERVO_3_CHANNEL 2
#define PWM_SERVO_3_CONF pwmcfg1
/* S3 pad is on the complementary channel TIM1_CH3N (PB15) */
#define PWM_SERVO_3_OUTPUT_MODE (PWM_OUTPUT_ACTIVE_HIGH | PWM_COMPLEMENTARY_OUTPUT_ACTIVE_HIGH)
#endif

#ifndef USE_PWM4
#define USE_PWM4 1
#endif
#if USE_PWM4
#define PWM_SERVO_4 4
#define PWM_SERVO_4_GPIO PAL_PORT(LINE_SERVO4)
#define PWM_SERVO_4_PIN PAL_PAD(LINE_SERVO4)
#define PWM_SERVO_4_AF AF_SERVO4
#define PWM_SERVO_4_DRIVER PWMD1
#define PWM_SERVO_4_CHANNEL 0
#define PWM_SERVO_4_CONF pwmcfg1
#endif

#ifndef USE_PWM5
#define USE_PWM5 1
#endif
#if USE_PWM5
#define PWM_SERVO_5 5
#define PWM_SERVO_5_GPIO PAL_PORT(LINE_SERVO5)
#define PWM_SERVO_5_PIN PAL_PAD(LINE_SERVO5)
#define PWM_SERVO_5_AF AF_SERVO5
#define PWM_SERVO_5_DRIVER PWMD2
#define PWM_SERVO_5_CHANNEL 3
#define PWM_SERVO_5_CONF pwmcfg2
#endif

#ifndef USE_PWM6
#define USE_PWM6 1
#endif
#if USE_PWM6
#define PWM_SERVO_6 6
#define PWM_SERVO_6_GPIO PAL_PORT(LINE_SERVO6)
#define PWM_SERVO_6_PIN PAL_PAD(LINE_SERVO6)
#define PWM_SERVO_6_AF AF_SERVO6
#define PWM_SERVO_6_DRIVER PWMD2
#define PWM_SERVO_6_CHANNEL 2
#define PWM_SERVO_6_CONF pwmcfg2
#endif

#ifndef USE_PWM7
#define USE_PWM7 1
#endif
#if USE_PWM7
#define PWM_SERVO_7 7
#define PWM_SERVO_7_GPIO PAL_PORT(LINE_SERVO7)
#define PWM_SERVO_7_PIN PAL_PAD(LINE_SERVO7)
#define PWM_SERVO_7_AF AF_SERVO7
#define PWM_SERVO_7_DRIVER PWMD2
#define PWM_SERVO_7_CHANNEL 1
#define PWM_SERVO_7_CONF pwmcfg2
#endif

#ifndef USE_PWM8
#define USE_PWM8 1
#endif
#if USE_PWM8
#define PWM_SERVO_8 8
#define PWM_SERVO_8_GPIO PAL_PORT(LINE_SERVO8)
#define PWM_SERVO_8_PIN PAL_PAD(LINE_SERVO8)
#define PWM_SERVO_8_AF AF_SERVO8
#define PWM_SERVO_8_DRIVER PWMD2
#define PWM_SERVO_8_CHANNEL 0
#define PWM_SERVO_8_CONF pwmcfg2
#endif

#ifndef USE_PWM9
#define USE_PWM9 1
#endif
#if USE_PWM9
#define PWM_SERVO_9 9
#define PWM_SERVO_9_GPIO PAL_PORT(LINE_SERVO9)
#define PWM_SERVO_9_PIN PAL_PAD(LINE_SERVO9)
#define PWM_SERVO_9_AF AF_SERVO9
#define PWM_SERVO_9_DRIVER PWMD12
#define PWM_SERVO_9_CHANNEL 0
#define PWM_SERVO_9_CONF pwmcfg12
#endif

#ifndef USE_PWM10
#define USE_PWM10 0 /* Disabled by default as TIM13 missing in paparazzi */
#endif
#if USE_PWM10
#define PWM_SERVO_10 10
#define PWM_SERVO_10_GPIO PAL_PORT(LINE_SERVO10)
#define PWM_SERVO_10_PIN PAL_PAD(LINE_SERVO10)
#define PWM_SERVO_10_AF AF_SERVO10
#define PWM_SERVO_10_DRIVER PWMD13
#define PWM_SERVO_10_CHANNEL 0
#define PWM_SERVO_10_CONF pwmcfg13
#endif

#ifndef USE_PWM11
#define USE_PWM11 1
#endif
#if USE_PWM11
#define PWM_SERVO_11 11
#define PWM_SERVO_11_GPIO PAL_PORT(LINE_SERVO11)
#define PWM_SERVO_11_PIN PAL_PAD(LINE_SERVO11)
#define PWM_SERVO_11_AF AF_SERVO11
#define PWM_SERVO_11_DRIVER PWMD4
#define PWM_SERVO_11_CHANNEL 0
#define PWM_SERVO_11_CONF pwmcfg4
#endif

#ifndef USE_PWM12
#define USE_PWM12 1
#endif
#if USE_PWM12
#define PWM_SERVO_12 12
#define PWM_SERVO_12_GPIO PAL_PORT(LINE_SERVO12)
#define PWM_SERVO_12_PIN PAL_PAD(LINE_SERVO12)
#define PWM_SERVO_12_AF AF_SERVO12
#define PWM_SERVO_12_DRIVER PWMD3
#define PWM_SERVO_12_CHANNEL 3
#define PWM_SERVO_12_CONF pwmcfg3
#endif

#define ACTUATORS_PWM_NB 13

#define UART1_GPIO_PORT_TX  PAL_PORT(LINE_USART1_TX)
#define UART1_GPIO_TX       PAL_PAD(LINE_USART1_TX)
#define UART1_GPIO_PORT_RX  PAL_PORT(LINE_USART1_RX)
#define UART1_GPIO_RX       PAL_PAD(LINE_USART1_RX)
#define UART1_GPIO_AF       AF_USART1_TX

#define UART2_GPIO_PORT_TX  PAL_PORT(LINE_USART2_TX)
#define UART2_GPIO_TX       PAL_PAD(LINE_USART2_TX)
#define UART2_GPIO_PORT_RX  PAL_PORT(LINE_USART2_RX)
#define UART2_GPIO_RX       PAL_PAD(LINE_USART2_RX)
#define UART2_GPIO_AF       AF_USART2_TX

#define UART3_GPIO_PORT_TX  PAL_PORT(LINE_USART3_TX)
#define UART3_GPIO_TX       PAL_PAD(LINE_USART3_TX)
#define UART3_GPIO_PORT_RX  PAL_PORT(LINE_USART3_RX)
#define UART3_GPIO_RX       PAL_PAD(LINE_USART3_RX)
#define UART3_GPIO_AF       AF_USART3_TX

#define UART4_GPIO_PORT_TX  PAL_PORT(LINE_UART4_TX)
#define UART4_GPIO_TX       PAL_PAD(LINE_UART4_TX)
#define UART4_GPIO_PORT_RX  PAL_PORT(LINE_UART4_RX)
#define UART4_GPIO_RX       PAL_PAD(LINE_UART4_RX)
#define UART4_GPIO_AF       AF_UART4_TX

#define UART5_GPIO_PORT_TX  PAL_PORT(LINE_UART5_TX)
#define UART5_GPIO_TX       PAL_PAD(LINE_UART5_TX)
#define UART5_GPIO_PORT_RX  PAL_PORT(LINE_UART5_RX)
#define UART5_GPIO_RX       PAL_PAD(LINE_UART5_RX)
#define UART5_GPIO_AF       AF_UART5_TX

#define UART6_GPIO_PORT_TX  PAL_PORT(LINE_USART6_TX)
#define UART6_GPIO_TX       PAL_PAD(LINE_USART6_TX)
#define UART6_GPIO_PORT_RX  PAL_PORT(LINE_USART6_RX)
#define UART6_GPIO_RX       PAL_PAD(LINE_USART6_RX)
#define UART6_GPIO_AF       AF_USART6_TX

#ifndef I2C1_CLOCK_SPEED
#define I2C1_CLOCK_SPEED 400000
#endif
#define I2C1_CFG_DEF { OPMODE_I2C, I2C1_CLOCK_SPEED, FAST_DUTY_CYCLE_2 }

#define SPI1_GPIO_AF          AF_SPI1_SCK
#define SPI1_GPIO_PORT_MISO   PAL_PORT(LINE_SPI1_MISO)
#define SPI1_GPIO_MISO        PAL_PAD(LINE_SPI1_MISO)
#define SPI1_GPIO_PORT_MOSI   PAL_PORT(LINE_SPI1_MOSI)
#define SPI1_GPIO_MOSI        PAL_PAD(LINE_SPI1_MOSI)
#define SPI1_GPIO_PORT_SCK    PAL_PORT(LINE_SPI1_SCK)
#define SPI1_GPIO_SCK         PAL_PAD(LINE_SPI1_SCK)

#define SPI2_GPIO_AF          AF_SPI2_SCK
#define SPI2_GPIO_PORT_MISO   PAL_PORT(LINE_SPI2_MISO)
#define SPI2_GPIO_MISO        PAL_PAD(LINE_SPI2_MISO)
#define SPI2_GPIO_PORT_MOSI   PAL_PORT(LINE_SPI2_MOSI)
#define SPI2_GPIO_MOSI        PAL_PAD(LINE_SPI2_MOSI)
#define SPI2_GPIO_PORT_SCK    PAL_PORT(LINE_SPI2_SCK)
#define SPI2_GPIO_SCK         PAL_PAD(LINE_SPI2_SCK)

/*
 * SPI slave selects:
 *  SLAVE0, SLAVE1, SLAVE6: ICM42688 IMU on SPI1 (PC14)
 *  SLAVE2: AT7456E OSD on SPI2 (PB12)
 *  SLAVE3: micro SD card on SPI2 (PC1)
 *  SLAVE4: dataflash on SPI2 (PC13)
 */
#define SPI_SELECT_SLAVE0_PORT  PAL_PORT(LINE_SPI1_CS)
#define SPI_SELECT_SLAVE0_PIN   PAL_PAD(LINE_SPI1_CS)
#define SPI_SELECT_SLAVE1_PORT  PAL_PORT(LINE_SPI1_CS)
#define SPI_SELECT_SLAVE1_PIN   PAL_PAD(LINE_SPI1_CS)
#define SPI_SELECT_SLAVE2_PORT  PAL_PORT(LINE_OSD_CS)
#define SPI_SELECT_SLAVE2_PIN   PAL_PAD(LINE_OSD_CS)
#define SPI_SELECT_SLAVE3_PORT  PAL_PORT(LINE_SDCARD_CS)
#define SPI_SELECT_SLAVE3_PIN   PAL_PAD(LINE_SDCARD_CS)
#define SPI_SELECT_SLAVE4_PORT  PAL_PORT(LINE_FLASH_CS)
#define SPI_SELECT_SLAVE4_PIN   PAL_PAD(LINE_FLASH_CS)
#define SPI_SELECT_SLAVE6_PORT  PAL_PORT(LINE_SPI1_CS)
#define SPI_SELECT_SLAVE6_PIN   PAL_PAD(LINE_SPI1_CS)

#define DEFAULT_ACTUATORS "modules/actuators/actuators_pwm.h"
#define ActuatorDefaultSet ActuatorPwmSet
#define ActuatorsDefaultInit() ActuatorsPwmInit()
#define ActuatorsDefaultCommit() ActuatorsPwmCommit()

#endif
