/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * symbolic_F_obm_u.c
 *
 * Code generation for function 'symbolic_F_obm_u'
 *
 */

/* Include files */
#include "cyclone_fu.h"
#include <math.h>

/* Function Definitions */
void cyclone_fu(const float v_e[3], const float w_e[3],
                      const float quat[4], const float u[4],
                      const float wind_e[3], const float coefficients[23],
                      float F_obm_u[49])
{
  float b_t326_tmp;
  float t13;
  float t137;
  float t138;
  float t139;
  float t14;
  float t15;
  float t16;
  float t160;
  float t162;
  float t164;
  float t166;
  float t168;
  float t17;
  float t170;
  float t172;
  float t174;
  float t18;
  float t185;
  float t186;
  float t189;
  float t19;
  float t193;
  float t194;
  float t197;
  float t20;
  float t21;
  float t211;
  float t230;
  float t232;
  float t259;
  float t266;
  float t267;
  float t268;
  float t272;
  float t273;
  float t274;
  float t28;
  float t281;
  float t282;
  float t283;
  float t28_tmp;
  float t29;
  float t293;
  float t294;
  float t295;
  float t296;
  float t297;
  float t298;
  float t299;
  float t300;
  float t302;
  float t311;
  float t313;
  float t32;
  float t320;
  float t326;
  float t326_tmp;
  float t327;
  float t328;
  float t329;
  float t33;
  float t330;
  float t331;
  float t333;
  float t334;
  float t335;
  float t337;
  float t370;
  float t372;
  float t373;
  float t386;
  float t387;
  float t389;
  float t394;
  float t413;
  float t42;
  float t421;
  float t422;
  float t429;
  float t43;
  float t430;
  float t432;
  float t43_tmp;
  float t47;
  float t51;
  float t55;
  float t58;
  float t59;
  float t63;
  float t67;
  float t71;
  (void)w_e;
  /* symbolic_F_obm_u */
  /*     F_obm_u = symbolic_F_obm_u(IN1,IN2,IN3,IN4,IN5,IN6) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-10-13 14:50:40 */
  t13 = v_e[2] + wind_e[2];
  t14 = v_e[1] + wind_e[1];
  t15 = v_e[0] + wind_e[0];
  t16 = u[2] * u[2];
  t17 = u[3] * u[3];
  t18 = quat[0] * quat[0];
  t19 = quat[1] * quat[1];
  t20 = quat[2] * quat[2];
  t21 = quat[3] * quat[3];
  t28_tmp = quat[0] * quat[1];
  t28 = t28_tmp * 2.0F;
  t137 = quat[0] * quat[2];
  t29 = t137 * 2.0F;
  t430 = quat[0] * quat[3];
  t387 = t430 * 2.0F;
  t386 = quat[1] * quat[2];
  t429 = t386 * 2.0F;
  t32 = quat[1] * quat[3] * 2.0F;
  t33 = quat[2] * quat[3] * 2.0F;
  t42 = quat[0] * v_e[0] * 2.0F;
  t43_tmp = quat[1] * v_e[2];
  t43 = t43_tmp * 2.0F;
  t47 = v_e[0] * quat[1] * 2.0F;
  t51 = v_e[0] * quat[2] * 2.0F;
  t55 = v_e[0] * quat[3] * 2.0F;
  t58 = quat[0] * wind_e[0] * 2.0F;
  t413 = quat[1] * wind_e[2];
  t59 = t413 * 2.0F;
  t63 = wind_e[0] * quat[1] * 2.0F;
  t67 = wind_e[0] * quat[2] * 2.0F;
  t71 = wind_e[0] * quat[3] * 2.0F;
  t230 = t137 * v_e[2] * -2.0F;
  t232 = t137 * wind_e[2] * -2.0F;
  t137 = t19 * 2.0F;
  t138 = t20 * 2.0F;
  t139 = t21 * 2.0F;
  t160 = t18 * v_e[0];
  t162 = t19 * v_e[0];
  t164 = t20 * v_e[0];
  t166 = t21 * v_e[0];
  t168 = t18 * wind_e[0];
  t170 = t19 * wind_e[0];
  t172 = t20 * wind_e[0];
  t174 = t21 * wind_e[0];
  t185 = t387 * v_e[1];
  t186 = t429 * v_e[1];
  t189 = t32 * v_e[2];
  t193 = t387 * wind_e[1];
  t194 = t429 * wind_e[1];
  t197 = t32 * wind_e[2];
  t211 = u[0] - u[1];
  t259 = t16 + t17;
  t266 = t28 + t33;
  t267 = t29 + t32;
  t268 = t387 + t429;
  t293 = ((t47 + v_e[1] * quat[2] * 2.0F) + t63) + wind_e[1] * quat[2] * 2.0F;
  t294 = ((t47 + v_e[2] * quat[3] * 2.0F) + t63) + wind_e[2] * quat[3] * 2.0F;
  t272 = t28 - t33;
  t273 = t29 - t32;
  t274 = t387 - t429;
  t281 = (t137 + t138) - 1.0F;
  t282 = (t137 + t139) - 1.0F;
  t283 = (t138 + t139) - 1.0F;
  t373 = quat[1] * v_e[1];
  t47 = quat[1] * wind_e[1];
  t295 = ((t373 * 2.0F + t47 * 2.0F) - t51) - t67;
  t296 = ((t43 + t59) - t55) - t71;
  t297 =
      ((((quat[0] * v_e[2] * 2.0F + t51) + quat[0] * wind_e[2] * 2.0F) + t67) -
       t373 * 4.0F) -
      t47 * 4.0F;
  t298 = ((((quat[0] * v_e[1] * 2.0F + t43_tmp * 4.0F) +
            quat[0] * wind_e[1] * 2.0F) +
           t413 * 4.0F) -
          t55) -
         t71;
  t47 = v_e[1] * quat[3];
  t63 = wind_e[1] * quat[3];
  t313 = quat[2] * v_e[2];
  t311 = quat[2] * wind_e[2];
  t299 =
      ((((t42 + t47 * 4.0F) + t58) + t63 * 4.0F) - t313 * 2.0F) - t311 * 2.0F;
  t300 =
      ((((t42 + t47 * 2.0F) + t58) + t63 * 2.0F) - t313 * 4.0F) - t311 * 4.0F;
  t63 = quat[1] * coefficients[4];
  t313 = quat[3] * coefficients[5];
  t311 = u[0] * coefficients[6];
  t326_tmp = t311 * quat[1];
  t43_tmp = u[1] * coefficients[6];
  b_t326_tmp = t43_tmp * quat[1];
  t389 = quat[2] * coefficients[5];
  t58 = quat[2] * coefficients[4];
  t394 = t311 * quat[2];
  t47 = quat[2] * coefficients[6] * -u[1];
  t326 = ((((((((((((((t63 * v_e[1] + t313 * v_e[1]) + t63 * wind_e[1]) +
                     t313 * wind_e[1]) +
                    t326_tmp * v_e[1]) +
                   b_t326_tmp * v_e[1]) +
                  t326_tmp * wind_e[1]) +
                 b_t326_tmp * wind_e[1]) -
                t389 * v_e[2]) -
               t58 * v_e[0]) -
              t389 * wind_e[2]) -
             t58 * wind_e[0]) -
            t394 * v_e[0]) +
           t47 * v_e[0]) -
          t394 * wind_e[0]) +
         t47 * wind_e[0];
  t413 = t43_tmp * quat[2];
  t432 = quat[0] * coefficients[5];
  t42 = quat[1] * coefficients[5];
  t329 = ((((((((((((((((t63 * v_e[0] + t58 * v_e[1]) + t63 * wind_e[0]) +
                       t58 * wind_e[1]) +
                      t326_tmp * v_e[0]) +
                     b_t326_tmp * v_e[0]) +
                    t394 * v_e[1]) +
                   t413 * v_e[1]) +
                  t326_tmp * wind_e[0]) +
                 b_t326_tmp * wind_e[0]) +
                t394 * wind_e[1]) +
               t413 * wind_e[1]) +
              coefficients[5] * t55) +
             coefficients[5] * t71) -
            t432 * v_e[1]) -
           t42 * v_e[2]) -
          t432 * wind_e[1]) -
         t42 * wind_e[2];
  t63 = quat[0] * coefficients[4];
  t137 = t311 * quat[0];
  t138 = t43_tmp * quat[0];
  t139 = quat[3] * coefficients[4];
  t373 = t311 * quat[3];
  t47 = quat[3] * coefficients[6] * -u[1];
  t59 = ((((((((((((((((((((t63 * v_e[1] + t389 * v_e[1]) + t313 * v_e[2]) +
                          t63 * wind_e[1]) +
                         t389 * wind_e[1]) +
                        t313 * wind_e[2]) +
                       t137 * v_e[1]) +
                      t138 * v_e[1]) +
                     t137 * wind_e[1]) +
                    t138 * wind_e[1]) +
                   coefficients[4] * t43) +
                  coefficients[4] * t59) +
                 t311 * t43) +
                t43_tmp * t43) +
               t311 * t59) +
              t43_tmp * t59) -
             t139 * v_e[0]) -
            t139 * wind_e[0]) -
           t373 * v_e[0]) +
          t47 * v_e[0]) -
         t373 * wind_e[0]) +
        t47 * wind_e[0];
  t47 = t43_tmp * quat[3];
  t335 = ((((((((((((((((((((((t432 * v_e[2] + t63 * v_e[0]) + t139 * v_e[1]) +
                             t432 * wind_e[2]) +
                            t63 * wind_e[0]) +
                           t139 * wind_e[1]) +
                          t137 * v_e[0]) +
                         t138 * v_e[0]) +
                        t373 * v_e[1]) +
                       t47 * v_e[1]) +
                      t137 * wind_e[0]) +
                     t138 * wind_e[0]) +
                    t373 * wind_e[1]) +
                   t47 * wind_e[1]) +
                  coefficients[5] * t51) +
                 coefficients[5] * t67) -
                t42 * v_e[1]) +
               t58 * v_e[2] * -2.0F) -
              t42 * wind_e[1]) +
             t58 * wind_e[2] * -2.0F) +
            t394 * v_e[2] * -2.0F) +
           t413 * v_e[2] * -2.0F) +
          t394 * wind_e[2] * -2.0F) +
         t413 * wind_e[2] * -2.0F;
  t327 = ((((((((((((((t18 * v_e[1] + t20 * v_e[1]) + t18 * wind_e[1]) +
                     t20 * wind_e[1]) +
                    t28 * v_e[2]) +
                   t429 * v_e[0]) +
                  t33 * v_e[2]) +
                 t28 * wind_e[2]) +
                t429 * wind_e[0]) +
               t33 * wind_e[2]) +
              t430 * v_e[0] * -2.0F) +
             t430 * wind_e[0] * -2.0F) -
            t19 * v_e[1]) -
           t21 * v_e[1]) -
          t19 * wind_e[1]) -
         t21 * wind_e[1];
  t328 = ((((((((((((((t160 + t162) + t168) + t170) + t185) + t186) + t189) +
                 t193) +
                t194) +
               t197) +
              t230) +
             t232) -
            t164) -
           t166) -
          t172) -
         t174;
  t47 = (((-(t19 * 2.0F) - t21 * 2.0F) + t430 * 0.0F) - t386 * 0.0F) + 1.0F;
  t139 = -t387 - (-t429);
  t311 = (t14 * t272 - t15 * t267) + t13 * t281;
  t63 = (t15 * t274 - t13 * t266) + t14 * t282;
  t313 = (t13 * t273 - t14 * t268) + t15 * t283;
  t302 = t47 * t47;
  t137 = 1.0F / t47;
  t138 = 1.0F / t302;
  t320 = 1.0F / (t302 + t139 * t139);
  t337 = sqrtf((t311 * t311 + t63 * t63) + t313 * t313);
  t333 = -(quat[0] * 2.0F) * t137 + quat[3] * 4.0F * t138 * t139;
  t370 = coefficients[10] * t311 * t337;
  t372 = coefficients[17] * t311 * t337;
  t373 = coefficients[6] * t311 * t337;
  t13 = quat[0] * coefficients[2] * t63 * t337 * 2.0F;
  t71 = quat[1] * coefficients[2] * t63 * t337;
  t55 = t71 * 2.0F;
  t43 = coefficients[2] * quat[2] * t63 * t337 * 2.0F;
  t14 = coefficients[2] * quat[3] * t63 * t337;
  t15 = t14 * 2.0F;
  t47 = 0.0F * t138 * t139 * 2.0F;
  t330 = quat[1] * t137 * 2.0F - t47;
  t331 = quat[3] * t137 * 2.0F - t47;
  t334 = quat[2] * 2.0F * t137 - -(quat[1] * 4.0F) * t138 * t139;
  t386 = coefficients[7] * t16 + t373;
  t387 = coefficients[7] * t17 + t373;
  t47 = coefficients[0] * t259 + coefficients[1] * t311 * t337;
  t389 = quat[0] * t47 * 2.0F;
  t58 = quat[1] * t47;
  t51 = t58 * 2.0F;
  t28 = quat[2] * t47;
  t67 = t28 * 2.0F;
  t394 = quat[3] * t47 * 2.0F;
  t47 =
      (((coefficients[3] * t259 + coefficients[7] * (u[0] * t16 + u[1] * t17)) +
        coefficients[4] * t311 * t337) -
       coefficients[5] * t313 * t337) +
      (u[0] + u[1]) * t373;
  t373 = quat[0] * t47 * 2.0F;
  t413 = quat[1] * t47 * 2.0F;
  t63 = quat[2] * t47;
  t137 = t63 * 2.0F;
  t326_tmp = quat[3] * t47;
  t47 = t326_tmp * 2.0F;
  b_t326_tmp = coefficients[1] * t267;
  t139 = coefficients[2] * t274;
  t421 = (((b_t326_tmp * t295 * t337 + t139 * t296 * t337) - t15) + t67) +
         t283 * t326 * t337 * 2.0F;
  t422 = (((b_t326_tmp * t298 * t337 + t139 * t297 * t337) + t43) + t394) +
         t283 * t59 * t337 * 2.0F;
  t432 = coefficients[2] * t266;
  t42 = coefficients[1] * t281;
  t274 = (((-(t432 * t296 * t337) - t42 * t295 * t337) + t55) +
          t273 * t326 * t337 * 2.0F) +
         t137;
  t43_tmp = coefficients[1] * t272;
  t138 = coefficients[2] * t282;
  t259 = (((t43_tmp * t295 * t337 - t138 * t296 * t337) + t51) +
          t268 * t326 * t337 * 2.0F) +
         t47;
  t429 = ((((t139 * t294 * t337 - b_t326_tmp * t300 * t337) + t55) + t389) -
          t283 * t335 * t337 * 2.0F) +
         t63 * 4.0F;
  t430 = ((((t432 * t297 * t337 + t42 * t298 * t337) - t13) + t58 * 4.0F) -
          t273 * t59 * t337 * 2.0F) +
         t47;
  t59 = ((((t43_tmp * t298 * t337 - t138 * t297 * t337) + t71 * 4.0F) + t389) +
         t268 * t59 * t337 * 2.0F) +
        t137;
  t43 = (((t42 * t293 * t337 + t432 * t299 * t337) + t43) -
         t273 * t329 * t337 * 2.0F) -
        t413;
  t71 = (((t138 * t294 * t337 + t43_tmp * t300 * t337) + t394) +
         t268 * t335 * t337 * 2.0F) -
        t413;
  t55 = ((((b_t326_tmp * t293 * t337 + t139 * t299 * t337) + t13) - t51) +
         t283 * t329 * t337 * 2.0F) -
        t326_tmp * 4.0F;
  t394 = ((((t43_tmp * t293 * t337 - t138 * t299 * t337) - t14 * 4.0F) + t67) +
          t268 * t329 * t337 * 2.0F) -
         t373;
  t432 = ((((t432 * t294 * t337 - t42 * t300 * t337) - t15) + t28 * 4.0F) +
          t273 * t335 * t337 * 2.0F) -
         t373;
  F_obm_u[0] = -t283 * t386;
  F_obm_u[1] = t268 * t386;
  F_obm_u[2] = -t273 * t386;
  F_obm_u[3] = 0.0F;
  F_obm_u[4] = 0.0F;
  F_obm_u[5] = t372 + coefficients[16] * t16;
  F_obm_u[6] = -t370 - coefficients[9] * t16;
  F_obm_u[7] = -t283 * t387;
  F_obm_u[8] = t268 * t387;
  F_obm_u[9] = -t273 * t387;
  F_obm_u[10] = 0.0F;
  F_obm_u[11] = 0.0F;
  F_obm_u[12] = t372 + coefficients[16] * t17;
  F_obm_u[13] = t370 + coefficients[9] * t17;
  t58 = coefficients[0] * u[2];
  t389 = u[2] * (coefficients[3] + u[0] * coefficients[7]);
  F_obm_u[14] = t58 * t267 * -2.0F - t389 * t283 * 2.0F;
  F_obm_u[15] = t58 * t272 * 2.0F + t389 * t268 * 2.0F;
  F_obm_u[16] = t58 * t281 * 2.0F - t389 * t273 * 2.0F;
  F_obm_u[17] = 0.0F;
  F_obm_u[18] = u[2] * coefficients[20] * 2.0F;
  F_obm_u[19] = u[2] * (coefficients[15] + u[0] * coefficients[16]) * 2.0F;
  F_obm_u[20] = u[2] * (coefficients[8] + u[0] * coefficients[9]) * -2.0F;
  t58 = coefficients[0] * u[3];
  t389 = u[3] * (coefficients[3] + u[1] * coefficients[7]);
  F_obm_u[21] = t58 * t267 * -2.0F - t389 * t283 * 2.0F;
  F_obm_u[22] = t58 * t272 * 2.0F + t389 * t268 * 2.0F;
  F_obm_u[23] = t58 * t281 * 2.0F - t389 * t273 * 2.0F;
  F_obm_u[24] = 0.0F;
  F_obm_u[25] = u[3] * coefficients[20] * -2.0F;
  F_obm_u[26] = u[3] * (coefficients[15] + u[1] * coefficients[16]) * 2.0F;
  F_obm_u[27] = u[3] * (coefficients[8] + u[1] * coefficients[9]) * 2.0F;
  F_obm_u[28] = ((quat[0] * t422 * -0.5F + quat[1] * t421 / 2.0F) -
                 quat[2] * t55 / 2.0F) -
                quat[3] * t429 / 2.0F;
  F_obm_u[29] =
      ((quat[0] * t59 / 2.0F - quat[1] * t259 / 2.0F) + quat[2] * t394 / 2.0F) -
      quat[3] * t71 / 2.0F;
  F_obm_u[30] =
      ((quat[0] * t430 / 2.0F + quat[1] * t274 / 2.0F) + quat[2] * t43 / 2.0F) +
      quat[3] * t432 / 2.0F;
  t58 = quat[0] * t302 * t320;
  t389 = quat[1] * t302 * t320;
  t42 = quat[2] * t302 * t320;
  b_t326_tmp = quat[3] * t302 * t320;
  F_obm_u[31] =
      ((t58 * t334 * -0.5F - t389 * t331 / 2.0F) + t42 * t333 / 2.0F) -
      b_t326_tmp * t330 / 2.0F;
  F_obm_u[32] = coefficients[19] * t337 *
                (((((((((((((((t18 * v_e[2] - t19 * v_e[2]) - t20 * v_e[2]) +
                             t21 * v_e[2]) +
                            t33 * v_e[1]) +
                           t29 * v_e[0]) +
                          t32 * v_e[0]) +
                         t18 * wind_e[2]) -
                        t19 * wind_e[2]) -
                       t20 * wind_e[2]) +
                      t21 * wind_e[2]) +
                     t33 * wind_e[1]) +
                    t29 * wind_e[0]) +
                   t32 * wind_e[0]) -
                  t28_tmp * v_e[1] * 2.0F) -
                 t28_tmp * wind_e[1] * 2.0F);
  t43_tmp = u[0] * coefficients[17];
  t413 = u[1] * coefficients[17];
  F_obm_u[33] = t327 * t337 * ((coefficients[12] + t43_tmp) + t413);
  F_obm_u[34] = -coefficients[10] * t211 * t327 * t337;
  F_obm_u[35] = ((quat[0] * t429 * -0.5F + quat[1] * t55 / 2.0F) +
                 quat[2] * t421 / 2.0F) +
                quat[3] * t422 / 2.0F;
  F_obm_u[36] = ((quat[0] * t71 * -0.5F - quat[1] * t394 / 2.0F) -
                 quat[2] * t259 / 2.0F) -
                quat[3] * t59 / 2.0F;
  F_obm_u[37] =
      ((quat[0] * t432 / 2.0F - quat[1] * t43 / 2.0F) + quat[2] * t274 / 2.0F) -
      quat[3] * t430 / 2.0F;
  F_obm_u[38] =
      ((t58 * t330 * -0.5F - t389 * t333 / 2.0F) - t42 * t331 / 2.0F) +
      b_t326_tmp * t334 / 2.0F;
  F_obm_u[39] = 0.0F;
  t326_tmp = coefficients[17] * -u[1];
  t311 = coefficients[13] * t18;
  t313 = coefficients[13] * t19;
  t373 = coefficients[13] * t20;
  t139 = coefficients[13] * t21;
  t138 = coefficients[13] * t33;
  t63 = coefficients[13] * t29;
  t137 = coefficients[13] * t32;
  t47 = quat[0] * coefficients[13] * quat[1];
    F_obm_u[40] = -t337 * (((((((((((((((((((((((((((((((((((((((((((((((((((((coefficients[12] * t160 + coefficients[12] * t162) + coefficients[12] * t168) + coefficients[12] * t170) + coefficients[12] * t185) + coefficients[12] * t186) + coefficients[12] * t189) + coefficients[12] * t193) + coefficients[12] * t194) + coefficients[12] * t197) + coefficients[12] * t230) + coefficients[12] * t232) + coefficients[12] * -t164) + coefficients[12] * -t166) + coefficients[12] * -t172) + coefficients[12] * -t174) + t43_tmp * t160) + t43_tmp * t162) + t413 * t160) + t43_tmp * t168) + t413 * t162) + t43_tmp * t170) + t413 * t168) + t413 * t170) + t43_tmp * t185) + t43_tmp * t186) + t43_tmp * t189) + t413 * t185) + t413 * t186) + t43_tmp * t193) + t43_tmp * t194) + t413 * t189) + t43_tmp * t197) + t413 * t193) + t413 * t194) + t413 * t197) + t43_tmp * t230) + t43_tmp * t232) + t413 * t230) + t413 * t232) + t43_tmp * -t164) + t43_tmp * -t166) + t43_tmp * -t172) + t43_tmp * -t174) + t326_tmp * t164) + t326_tmp * t166) + t326_tmp * t172) + t326_tmp * t174) + t311 * v_e[2]) - t313 * v_e[2]) - t373 * v_e[2]) + t139 * v_e[2]) + t138 * v_e[1]) + ((((((((((t63 * v_e[0] + t137 * v_e[0]) + t311 * wind_e[2]) - t313 * wind_e[2]) - t373 * wind_e[2]) + t139 * wind_e[2]) + t138 * wind_e[1]) + t63 * wind_e[0]) + t137 * wind_e[0]) - t47 * v_e[1] * 2.0F) - t47 * wind_e[1] * 2.0F));
    F_obm_u[41] = coefficients[10] * t211 * t328 * t337;
    F_obm_u[42] = ((quat[0] * t55 / 2.0F + quat[1] * t429 / 2.0F) -
                   quat[2] * t422 / 2.0F) +
                  quat[3] * t421 / 2.0F;
    F_obm_u[43] = ((quat[0] * t394 * -0.5F + quat[1] * t71 / 2.0F) +
                   quat[2] * t59 / 2.0F) -
                  quat[3] * t259 / 2.0F;
    F_obm_u[44] = ((quat[0] * t43 * -0.5F - quat[1] * t432 / 2.0F) +
                   quat[2] * t430 / 2.0F) +
                  quat[3] * t274 / 2.0F;
    F_obm_u[45] =
        ((t58 * t333 * -0.5F + t389 * t330 / 2.0F) - t42 * t334 / 2.0F) -
        b_t326_tmp * t331 / 2.0F;
    F_obm_u[46] = -coefficients[19] * t328 * t337;
    F_obm_u[47] = coefficients[13] * t327 * t337;
    F_obm_u[48] = 0.0F;
}

/* End of code generation (cyclone_fu.c) */
